name: Balance Check
on: [push]
jobs:
  csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install pandas
      - run: python scripts/balance_check.py