name: Build & Export
on: [push, pull_request]
jobs:
  godot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.2.1
          use-dotnet: false
      - run: godot --headless --export-release "Web" ./build/web/index.html
      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: ./build/web